### ISSUE TITLE
Incompatible <input> font size styles between Desktop and Mobile Devices Browsers

### ISSUE THREAD

**Issue by v4ex-inc** [v4ex/V4EX-UI#1]
* React Search Box https://codepen.io/xuwei-li/pen/bGRQbve
* React Search Bar https://codepen.io/xuwei-li/pen/ExXOjMd

```html
<input id="search-input" value={this.state.searchInput} onChange={this.handleSearchInput}></input>
```

```css
#search-input {
  border: none;
  outline: none;
  font-size: 2rem;
  margin-right: 1rem;
  width: 100%;
}
```

# Solution
```css
@media only screen and (max-width: 600px) {
  #search-input {
    font-size: 1rem;
  }
}
```

# References
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search
* https://www.w3schools.com/html/html_form_input_types.asp
* https://medium.com/@rion.mrk/how-to-remove-x-icon-from-search-input-field-or-input-type-search-db3c808405fb
* https://css-tricks.com/webkit-html5-search-inputs/
* https://css-tricks.com/almanac/properties/f/font-size/#article-header-id-7
* https://css-tricks.com/fitting-text-to-a-container/
* 👍 https://www.mydevice.io/
